import React from 'react'
import './RightSidebar.css'
import chat from '../../../assests/chat-2-fill.png'
import pen from '../../../assests/pencil-fill.png'
import sofline from '../../../assests/stack-overflow-line.png'

const Widget = () => {
  return (
    


<div className="widget">

<h4>The Overflow Blog</h4>
<div className="right-sidebar-div-1">
<img src={pen} alt="pen" width='18'/>
<p>
Remote work is killing big offices. Cities must change to survive
</p>


</div>
<div className="right-sidebar-div-2">
<img src={pen} alt="pen" width='18'/>
<p>
You should be reading academic computer science papers
</p>


</div>

<h4>Fetured on Meta</h4>
<div className="right-sidebar-div-1">
<img src={chat} alt="pen" width='18'/>
<p>
Navigation and UI research starting soon.
</p>


</div>
<div className="right-sidebar-div-2">
<img src={chat} alt="pen" width='18'/>
<p>
Navigation and UI research starting soon
Temporary policy: ChatGPT is banned
</p>


</div>
<div className="right-sidebar-div-2">
<img src={sofline} alt="pen" width='18'/>
<p>
Should we burninate the [choice] tag?
</p>


</div>

<h4>Hot meta posts</h4>
<div className="right-sidebar-div-1">
    <p>48</p>
<p>

How to flag dozens of almost identical answers

</p>


</div>
<div className="right-sidebar-div-2">
<p>75</p>
<p>
Should we flag human-written questions that use code generated by ChatGPT?
</p>


</div>







</div>

  )
}

export default Widget